"""
Sitewide UI-copy guards.

House rule: an em dash never appears as a connector in user-facing copy; the
voice uses two sentences, a comma, or a middle dot instead. Earlier guards
checked single surfaces (digest, operator table) and greps looked for the
literal character, which let `\\u2014` escapes in JS strings ship unnoticed.
This scans every frontend page.

A lone quoted em dash ('\\u2014' or '—') is the missing-value placeholder
glyph and is allowed. Comments (HTML, CSS, JS) are not user-visible copy and
are ignored.
"""

import re
from pathlib import Path

import pytest

FRONTEND = Path(__file__).parent.parent / "frontend"

# Placeholder form: the em dash alone inside quotes/backticks.
_LONE_GLYPH = re.compile(r"""(['"`])(?:\\u2014|—)\1""")

# A regex character class like [—\-] parses copy rather than emitting it.
_CHAR_CLASS = re.compile(r"\[[^\]\n]*—[^\]\n]*\]")

_HTML_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)

# ops.html is the token-gated internal dashboard; its bare — glyphs are
# loading placeholders between tags, not public copy.
_EXCLUDED = {"ops.html"}


def _strip_non_copy(text: str) -> str:
    text = _HTML_COMMENT.sub("", text)
    text = _BLOCK_COMMENT.sub("", text)
    # Whole-line JS comments. Inline trailing // is left alone: it can sit
    # inside a URL or string, and real copy never lives after one anyway.
    lines = []
    for line in text.splitlines():
        if line.lstrip().startswith(("//", "*")):
            continue
        lines.append(line)
    return "\n".join(lines)


def _pages():
    return sorted(p for p in FRONTEND.glob("*.html") if p.name not in _EXCLUDED)


class TestNoEmDashConnectors:
    def test_frontend_pages_exist(self):
        assert len(_pages()) > 5, f"expected frontend pages in {FRONTEND}"

    @pytest.mark.parametrize("page", _pages(), ids=lambda p: p.name)
    def test_no_em_dash_in_ui_copy(self, page):
        raw = page.read_text(encoding="utf-8", errors="replace")
        cleaned = _strip_non_copy(raw)
        cleaned = _LONE_GLYPH.sub("", cleaned)
        cleaned = _CHAR_CLASS.sub("", cleaned)

        offenders = []
        for lineno, line in enumerate(cleaned.splitlines(), start=1):
            if "—" in line or "\\u2014" in line or "&mdash;" in line:
                offenders.append(f"  ~line {lineno}: {line.strip()[:120]}")
        assert not offenders, (
            f"{page.name} has em-dash connectors in UI copy "
            f"(use two sentences, a comma, or ' · '):\n" + "\n".join(offenders)
        )


# The scan above reads frontend/*.html. That is the static half of the site.
# The other half, and by URL count much the larger one, is generated by
# api/routes/frontend.py: 1,792 /property pages, 122 /llc, 177 /neighborhood,
# and every hub. None of it was covered, so the house rule held only where it
# happened to be checked. Scanning the rendered page rather than the Python
# source keeps comments and docstrings out of it, which is the same distinction
# _strip_non_copy draws for HTML.

# Static pages are covered by the frontend/*.html scan above; these are the
# routes the app itself renders. /brooklyn reaches the app as /borough/brooklyn
# through an nginx rewrite, so the app path is the one to ask for.
_SSR_ROUTES = [
    "/evictions", "/who-owns-my-building", "/is-my-building-rent-stabilized",
    "/displacement", "/operators", "/neighborhoods", "/flips", "/radar",
    "/this-week", "/llc", "/borough/brooklyn", "/flips/editions",
    "/neighborhood/11216?lang=es",
]

_CHROME_TAGS = re.compile(r"<(script|style)\b.*?</\1>", re.DOTALL | re.IGNORECASE)


def _ssr_sample():
    """The standing routes plus one live page from each per-record template."""
    from sqlalchemy import text

    from models.database import SessionLocal

    routes = list(_SSR_ROUTES)
    db = SessionLocal()
    try:
        bbl = db.execute(text(
            "SELECT p.bbl FROM parcels p WHERE p.address IS NOT NULL "
            "AND EXISTS (SELECT 1 FROM ownership_raw o WHERE o.bbl = p.bbl) LIMIT 1"
        )).scalar()
        if bbl:
            routes.append(f"/property/{bbl}")
        slug = db.execute(text(
            "SELECT btrim(regexp_replace(lower(party_name_normalized), "
            "'[^a-z0-9]+', '-', 'g'), '-') FROM ownership_raw "
            "WHERE doc_type = 'DEED' AND party_type = '2' "
            "AND party_name_normalized LIKE '%LLC%' "
            "GROUP BY 1, party_name_normalized HAVING count(DISTINCT bbl) >= 3 LIMIT 1"
        )).scalar()
        if slug:
            routes.append(f"/llc/{slug}")
        zip_code = db.execute(text(
            "SELECT zip_code FROM displacement_scores WHERE score IS NOT NULL LIMIT 1"
        )).scalar()
        if zip_code:
            routes.append(f"/neighborhood/{zip_code}")
    finally:
        db.close()
    return routes


class TestNoEmDashInRenderedPages:
    @pytest.fixture(scope="class")
    def client(self):
        from fastapi.testclient import TestClient

        from api.main import app
        return TestClient(app)

    @pytest.mark.parametrize("route", _ssr_sample(), ids=lambda r: r.strip("/") or "home")
    def test_no_em_dash_in_rendered_copy(self, client, route):
        resp = client.get(route)
        if resp.status_code != 200:
            pytest.skip(f"{route} returned {resp.status_code}")
        body = _CHROME_TAGS.sub(" ", resp.text.split("<body", 1)[-1])
        # The lone glyph between tags is the missing-value placeholder.
        body = re.sub(r">\s*(—|&mdash;)\s*<", "><", body)
        assert "—" not in body and "&mdash;" not in body, (
            f"{route} renders an em-dash connector in visible copy "
            f"(use two sentences, a comma, or ' · ')"
        )
