"""initial_schema

Revision ID: 0e9b19eaba99
Revises: 
Create Date: 2026-04-11 07:39:58.863316

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e9b19eaba99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints_raw',
    sa.Column('unique_key', sa.String(length=20), nullable=False),
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('complaint_type', sa.String(length=100), nullable=True),
    sa.Column('descriptor', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('borough', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('agency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_key', name='uq_complaints_raw_unique_key')
    )
    op.create_index('idx_complaints_raw_bbl', 'complaints_raw', ['bbl'], unique=False)
    op.create_index('idx_complaints_raw_created_at', 'complaints_raw', ['created_at'], unique=False)
    op.create_index('idx_complaints_raw_created_date', 'complaints_raw', ['created_date'], unique=False)
    # idx_complaints_raw_location is created automatically by geoalchemy2 spatial_index=True during create_table
    op.create_index('idx_complaints_raw_zip_code', 'complaints_raw', ['zip_code'], unique=False)
    op.create_table('displacement_scores',
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('signal_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('permit_intensity', sa.Float(), nullable=True),
    sa.Column('eviction_rate', sa.Float(), nullable=True),
    sa.Column('llc_acquisition_rate', sa.Float(), nullable=True),
    sa.Column('assessment_spike', sa.Float(), nullable=True),
    sa.Column('complaint_rate', sa.Float(), nullable=True),
    sa.Column('cache_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_last_updated', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zip_code', name='uq_displacement_scores_zip_code')
    )
    op.create_index('idx_displacement_scores_score', 'displacement_scores', ['score'], unique=False)
    op.create_index('idx_displacement_scores_zip_code', 'displacement_scores', ['zip_code'], unique=False)
    op.create_table('evictions_raw',
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('docket_number', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('borough', sa.String(length=20), nullable=True),
    sa.Column('eviction_type', sa.String(length=50), nullable=True),
    sa.Column('executed_date', sa.Date(), nullable=True),
    sa.Column('court_index_number', sa.String(length=30), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bbl', 'executed_date', 'docket_number', name='uq_evictions_raw_bbl_date_docket')
    )
    op.create_index('idx_evictions_raw_bbl', 'evictions_raw', ['bbl'], unique=False)
    op.create_index('idx_evictions_raw_created_at', 'evictions_raw', ['created_at'], unique=False)
    op.create_index('idx_evictions_raw_executed_date', 'evictions_raw', ['executed_date'], unique=False)
    op.create_index('idx_evictions_raw_zip_code', 'evictions_raw', ['zip_code'], unique=False)
    op.create_table('neighborhoods',
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('borough', sa.String(length=20), nullable=True),
    sa.Column('borough_code', sa.Integer(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zip_code', name='uq_neighborhoods_zip_code')
    )
    # idx_neighborhoods_geometry is created automatically by geoalchemy2 spatial_index=True during create_table
    op.create_index('idx_neighborhoods_zip_code', 'neighborhoods', ['zip_code'], unique=False)
    op.create_table('ownership_raw',
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('document_id', sa.String(length=20), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('party_type', sa.String(length=10), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('party_name_normalized', sa.String(length=200), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('doc_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'party_type', name='uq_ownership_raw_document_party')
    )
    op.create_index('idx_ownership_raw_bbl', 'ownership_raw', ['bbl'], unique=False)
    op.create_index('idx_ownership_raw_created_at', 'ownership_raw', ['created_at'], unique=False)
    op.create_index('idx_ownership_raw_doc_date', 'ownership_raw', ['doc_date'], unique=False)
    op.create_index('idx_ownership_raw_doc_type', 'ownership_raw', ['doc_type'], unique=False)
    op.create_index('idx_ownership_raw_party_name_norm', 'ownership_raw', ['party_name_normalized'], unique=False)
    op.create_table('parcels',
    sa.Column('bbl', sa.String(length=10), nullable=False),
    sa.Column('borough', sa.Integer(), nullable=True),
    sa.Column('block', sa.String(length=5), nullable=True),
    sa.Column('lot', sa.String(length=4), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('units_res', sa.Integer(), nullable=True),
    sa.Column('units_total', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('lot_area', sa.Float(), nullable=True),
    sa.Column('bldg_area', sa.Float(), nullable=True),
    sa.Column('zoning_dist', sa.String(length=20), nullable=True),
    sa.Column('land_use', sa.String(length=2), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_type', sa.String(length=10), nullable=True),
    sa.Column('on_speculation_watch_list', sa.Boolean(), nullable=False),
    sa.Column('assessed_total', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bbl', name='uq_parcels_bbl')
    )
    op.create_index('idx_parcels_bbl', 'parcels', ['bbl'], unique=False)
    # idx_parcels_geometry is created automatically by geoalchemy2 spatial_index=True during create_table
    op.create_index('idx_parcels_zip_code', 'parcels', ['zip_code'], unique=False)
    op.create_table('permits_raw',
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('bin', sa.String(length=7), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('borough', sa.String(length=20), nullable=True),
    sa.Column('permit_type', sa.String(length=10), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bbl', 'filing_date', 'permit_type', 'work_type', name='uq_permits_raw_bbl_date_type_work')
    )
    op.create_index('idx_permits_raw_bbl', 'permits_raw', ['bbl'], unique=False)
    op.create_index('idx_permits_raw_created_at', 'permits_raw', ['created_at'], unique=False)
    op.create_index('idx_permits_raw_filing_date', 'permits_raw', ['filing_date'], unique=False)
    op.create_index('idx_permits_raw_zip_code', 'permits_raw', ['zip_code'], unique=False)
    op.create_table('property_scores',
    sa.Column('bbl', sa.String(length=10), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('signal_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cache_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bbl', name='uq_property_scores_bbl')
    )
    op.create_index('idx_property_scores_bbl', 'property_scores', ['bbl'], unique=False)
    op.create_index('idx_property_scores_score', 'property_scores', ['score'], unique=False)
    op.create_index('idx_property_scores_zip_code', 'property_scores', ['zip_code'], unique=False)
    op.create_table('sales_raw',
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('building_class', sa.String(length=10), nullable=True),
    sa.Column('gross_sqft', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('borough', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bbl', 'sale_date', 'sale_price', name='uq_sales_raw_bbl_date_price')
    )
    op.create_index('idx_sales_raw_bbl', 'sales_raw', ['bbl'], unique=False)
    op.create_index('idx_sales_raw_created_at', 'sales_raw', ['created_at'], unique=False)
    op.create_index('idx_sales_raw_sale_date', 'sales_raw', ['sale_date'], unique=False)
    op.create_index('idx_sales_raw_zip_code', 'sales_raw', ['zip_code'], unique=False)
    op.create_table('scraper_quarantine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scraper_name', sa.String(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quarantine_created_at', 'scraper_quarantine', ['created_at'], unique=False)
    op.create_index('idx_quarantine_scraper_name', 'scraper_quarantine', ['scraper_name'], unique=False)
    op.create_table('scraper_runs',
    sa.Column('scraper_name', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('expected_min_records', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('watermark_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scraper_runs_scraper_name', 'scraper_runs', ['scraper_name'], unique=False)
    op.create_index('idx_scraper_runs_started_at', 'scraper_runs', ['started_at'], unique=False)
    op.create_index('idx_scraper_runs_status', 'scraper_runs', ['status'], unique=False)
    op.create_table('subscribers',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'zip_code', name='uq_subscribers_email_zip'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_index('idx_subscribers_confirmed', 'subscribers', ['confirmed'], unique=False)
    op.create_index('idx_subscribers_email', 'subscribers', ['email'], unique=False)
    op.create_index('idx_subscribers_zip_code', 'subscribers', ['zip_code'], unique=False)
    op.create_table('violations_raw',
    sa.Column('violation_id', sa.String(length=20), nullable=False),
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('borough', sa.String(length=20), nullable=True),
    sa.Column('violation_class', sa.String(length=1), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('nov_issued_date', sa.Date(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('violation_id', name='uq_violations_raw_violation_id')
    )
    op.create_index('idx_violations_raw_bbl', 'violations_raw', ['bbl'], unique=False)
    op.create_index('idx_violations_raw_class', 'violations_raw', ['violation_class'], unique=False)
    op.create_index('idx_violations_raw_created_at', 'violations_raw', ['created_at'], unique=False)
    op.create_index('idx_violations_raw_inspection_date', 'violations_raw', ['inspection_date'], unique=False)
    op.create_index('idx_violations_raw_zip_code', 'violations_raw', ['zip_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_violations_raw_zip_code', table_name='violations_raw')
    op.drop_index('idx_violations_raw_inspection_date', table_name='violations_raw')
    op.drop_index('idx_violations_raw_created_at', table_name='violations_raw')
    op.drop_index('idx_violations_raw_class', table_name='violations_raw')
    op.drop_index('idx_violations_raw_bbl', table_name='violations_raw')
    op.drop_table('violations_raw')
    op.drop_index('idx_subscribers_zip_code', table_name='subscribers')
    op.drop_index('idx_subscribers_email', table_name='subscribers')
    op.drop_index('idx_subscribers_confirmed', table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index('idx_scraper_runs_status', table_name='scraper_runs')
    op.drop_index('idx_scraper_runs_started_at', table_name='scraper_runs')
    op.drop_index('idx_scraper_runs_scraper_name', table_name='scraper_runs')
    op.drop_table('scraper_runs')
    op.drop_index('idx_quarantine_scraper_name', table_name='scraper_quarantine')
    op.drop_index('idx_quarantine_created_at', table_name='scraper_quarantine')
    op.drop_table('scraper_quarantine')
    op.drop_index('idx_sales_raw_zip_code', table_name='sales_raw')
    op.drop_index('idx_sales_raw_sale_date', table_name='sales_raw')
    op.drop_index('idx_sales_raw_created_at', table_name='sales_raw')
    op.drop_index('idx_sales_raw_bbl', table_name='sales_raw')
    op.drop_table('sales_raw')
    op.drop_index('idx_property_scores_zip_code', table_name='property_scores')
    op.drop_index('idx_property_scores_score', table_name='property_scores')
    op.drop_index('idx_property_scores_bbl', table_name='property_scores')
    op.drop_table('property_scores')
    op.drop_index('idx_permits_raw_zip_code', table_name='permits_raw')
    op.drop_index('idx_permits_raw_filing_date', table_name='permits_raw')
    op.drop_index('idx_permits_raw_created_at', table_name='permits_raw')
    op.drop_index('idx_permits_raw_bbl', table_name='permits_raw')
    op.drop_table('permits_raw')
    op.drop_index('idx_parcels_zip_code', table_name='parcels')
    # idx_parcels_geometry is dropped automatically with the table (geoalchemy2 managed)
    op.drop_index('idx_parcels_bbl', table_name='parcels')
    op.drop_table('parcels')
    op.drop_index('idx_ownership_raw_party_name_norm', table_name='ownership_raw')
    op.drop_index('idx_ownership_raw_doc_type', table_name='ownership_raw')
    op.drop_index('idx_ownership_raw_doc_date', table_name='ownership_raw')
    op.drop_index('idx_ownership_raw_created_at', table_name='ownership_raw')
    op.drop_index('idx_ownership_raw_bbl', table_name='ownership_raw')
    op.drop_table('ownership_raw')
    op.drop_index('idx_neighborhoods_zip_code', table_name='neighborhoods')
    # idx_neighborhoods_geometry is dropped automatically with the table (geoalchemy2 managed)
    op.drop_table('neighborhoods')
    op.drop_index('idx_evictions_raw_zip_code', table_name='evictions_raw')
    op.drop_index('idx_evictions_raw_executed_date', table_name='evictions_raw')
    op.drop_index('idx_evictions_raw_created_at', table_name='evictions_raw')
    op.drop_index('idx_evictions_raw_bbl', table_name='evictions_raw')
    op.drop_table('evictions_raw')
    op.drop_index('idx_displacement_scores_zip_code', table_name='displacement_scores')
    op.drop_index('idx_displacement_scores_score', table_name='displacement_scores')
    op.drop_table('displacement_scores')
    op.drop_index('idx_complaints_raw_zip_code', table_name='complaints_raw')
    # idx_complaints_raw_location is dropped automatically with the table (geoalchemy2 managed)
    op.drop_index('idx_complaints_raw_created_date', table_name='complaints_raw')
    op.drop_index('idx_complaints_raw_created_at', table_name='complaints_raw')
    op.drop_index('idx_complaints_raw_bbl', table_name='complaints_raw')
    op.drop_table('complaints_raw')
    # ### end Alembic commands ###
