"""add_score_history

Revision ID: 79ca1ee6134b
Revises: 0e9b19eaba99
Create Date: 2026-04-12 14:35:15.086552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ca1ee6134b'
down_revision: Union[str, None] = '0e9b19eaba99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_history',
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('scored_at', sa.Date(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('permit_intensity', sa.Float(), nullable=True),
    sa.Column('eviction_rate', sa.Float(), nullable=True),
    sa.Column('llc_acquisition_rate', sa.Float(), nullable=True),
    sa.Column('assessment_spike', sa.Float(), nullable=True),
    sa.Column('complaint_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zip_code', 'scored_at', name='uq_score_history_zip_date')
    )
    op.create_index('idx_score_history_zip_scored_at', 'score_history', ['zip_code', 'scored_at'], unique=False, postgresql_ops={'scored_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_score_history_zip_scored_at', table_name='score_history', postgresql_ops={'scored_at': 'DESC'})
    op.drop_table('score_history')
    # ### end Alembic commands ###
