"""add_rs_buildings

Revision ID: b0b44943f886
Revises: eb36d40ffc5d
Create Date: 2026-04-12 14:48:24.148989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0b44943f886'
down_revision: Union[str, None] = 'eb36d40ffc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rs_buildings',
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rs_unit_count', sa.Integer(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bbl', 'year', name='uq_rs_buildings_bbl_year')
    )
    op.create_index('idx_rs_buildings_bbl', 'rs_buildings', ['bbl'], unique=False)
    op.create_index('idx_rs_buildings_year', 'rs_buildings', ['year'], unique=False)
    op.drop_index('idx_score_history_zip_scored_at', table_name='score_history')
    op.create_index('idx_score_history_zip_scored_at', 'score_history', ['zip_code', 'scored_at'], unique=False, postgresql_ops={'scored_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_score_history_zip_scored_at', table_name='score_history', postgresql_ops={'scored_at': 'DESC'})
    op.create_index('idx_score_history_zip_scored_at', 'score_history', ['zip_code', sa.text('scored_at DESC')], unique=False)
    op.drop_index('idx_rs_buildings_year', table_name='rs_buildings')
    op.drop_index('idx_rs_buildings_bbl', table_name='rs_buildings')
    op.drop_table('rs_buildings')
    # ### end Alembic commands ###
