"""add_dcwp_licenses

Revision ID: eb36d40ffc5d
Revises: 79ca1ee6134b
Create Date: 2026-04-12 14:46:40.200189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb36d40ffc5d'
down_revision: Union[str, None] = '79ca1ee6134b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dcwp_licenses',
    sa.Column('license_nbr', sa.String(length=30), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('dba_trade_name', sa.String(length=200), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('license_status', sa.String(length=50), nullable=True),
    sa.Column('license_creation_date', sa.Date(), nullable=True),
    sa.Column('lic_expir_dd', sa.Date(), nullable=True),
    sa.Column('address_building', sa.String(length=20), nullable=True),
    sa.Column('address_street_name', sa.String(length=200), nullable=True),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('address_borough', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_nbr', name='uq_dcwp_license_nbr')
    )
    op.create_index('idx_dcwp_licenses_category', 'dcwp_licenses', ['business_category'], unique=False)
    op.create_index('idx_dcwp_licenses_creation_date', 'dcwp_licenses', ['license_creation_date'], unique=False)
    op.create_index('idx_dcwp_licenses_zip', 'dcwp_licenses', ['address_zip'], unique=False)
    op.drop_index('idx_score_history_zip_scored_at', table_name='score_history')
    op.create_index('idx_score_history_zip_scored_at', 'score_history', ['zip_code', 'scored_at'], unique=False, postgresql_ops={'scored_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_score_history_zip_scored_at', table_name='score_history', postgresql_ops={'scored_at': 'DESC'})
    op.create_index('idx_score_history_zip_scored_at', 'score_history', ['zip_code', sa.text('scored_at DESC')], unique=False)
    op.drop_index('idx_dcwp_licenses_zip', table_name='dcwp_licenses')
    op.drop_index('idx_dcwp_licenses_creation_date', table_name='dcwp_licenses')
    op.drop_index('idx_dcwp_licenses_category', table_name='dcwp_licenses')
    op.drop_table('dcwp_licenses')
    # ### end Alembic commands ###
